import Head from 'next/head'
import Header from '@/components/Header'
import SecondaryHeader from '@/components/SecondaryHeader'
import { useState } from 'react'
import Canva from '@/components/Canva'

export default function Home() {
  const [boxQuantity, setBoxQuantity] = useState(0)
  const [boxSize, setBoxSize] = useState(0)

  const [flexDirection, setFlexDirection] = useState('row')
  const [flexWrap, setFlexWrap] = useState('wrap')
  const [justifyContent, setJustifyContent] = useState('flex-start')
  const [alignItems, setAlignItems] = useState('flex-start')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setBoxQuantity={setBoxQuantity} setBoxSize={setBoxSize}/>
      <SecondaryHeader setAlignItems={setAlignItems} setFlexDirection={setFlexDirection} setFlexWrap={setFlexWrap} setJustifyContent={setJustifyContent}/>
      <Canva boxQuantity={boxQuantity} boxSize={boxSize} flexDirection={flexDirection} flexWrap={flexWrap} alignItems={alignItems} justifyContent={justifyContent} />
    </>
  )
}
